"""change cooktime to datatype interval

Revision ID: bcc6b02b23f1
Revises: cc42ad297ece
Create Date: 2023-02-28 12:51:31.799364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc6b02b23f1'
down_revision = 'cc42ad297ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('cook_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Interval(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('cook_time',
               existing_type=sa.Interval(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
